name: Deploy to Main

on:
  pull_request:
    types: [closed]     # triggers when PR is closed (merged)
    branches:
      - main            # only for PRs targeting 'main'

jobs:
  deploy-main:
    # Run only when PR was merged successfully
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Production Org
        run: echo "${{ secrets.PROD_SF_AUTH_URL }}" | sf auth:sfdxurl:store --alias Production --sfdx-url-stdin

      - name: Deploy Metadata to Production
        run: sf project deploy start --source-dir force-app/main/default --target-org Production --wait 10

      - name: Send Email on Deploy to Main Failure
        if: failure()
        uses: Padmachilaka/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deploy to Main (Production) Failure"
          to: padduja712@gmail.com
          from: ci-cd@yourcompany.com
          body: |
            Deployment to Production failed after merging PR from uat to main.
            Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
