
name: Email Alert on Failure

on:
  workflow_run:
    workflows: ["Validation", "Apex Tests", "Deploy to Dev", "Deploy to UAT", "Deploy to Production"]
    types:
      - completed

jobs:
  send-failure-email:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
    - name: Send Failure Email Notification
      uses: Padmachilaka/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "üö® CI/CD Pipeline Failure Alert"
        to: padduja712@gmail.com
        from: ci-cd@yourcompany.com
        body: |
          ‚ö†Ô∏è The CI/CD pipeline failed.
          Workflow Name: ${{ github.event.workflow_run.name }}
          Branch: ${{ github.event.workflow_run.head_branch }}
          Run Number: ${{ github.event.workflow_run.run_number }}
          Logs: ${{ github.event.workflow_run.html_url }}
